name: flutter_application_1
description: A creative notepad app with local authentication and SQLite storage

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  big_decimal: ^0.1.0
  pluto_grid: ^7.0.2  
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+1
  path: ^1.8.3
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  provider: ^6.1.1  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


